# Generated by Django 4.1 on 2022-10-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0004_remove_profile_image_profile_short_listed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='viewed',
            field=models.BooleanField(default=False),
        ),
    ]
