# Generated by Django 4.1.1 on 2022-10-30 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0006_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='jobvacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=20)),
                ('noofvacancy', models.IntegerField()),
                ('role', models.CharField(max_length=30)),
            ],
        ),
    ]
