# Generated by Django 4.1 on 2022-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0007_jobvacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='Verified',
            field=models.BooleanField(default=False),
        ),
    ]
