# Generated by Django 4.1 on 2022-12-08 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0011_profile_appointed_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejected',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar', models.IntegerField()),
            ],
        ),
    ]
