# Generated by Django 4.1 on 2022-12-08 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0012_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='aadhar',
            field=models.IntegerField(null=True),
        ),
    ]
