# Generated by Django 4.1 on 2022-12-08 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0013_profile_aadhar'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal_publication',
            name='indexed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='journal_publication',
            name='unindexed',
            field=models.BooleanField(default=False),
        ),
    ]
