# Generated by Django 4.1 on 2022-12-08 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('create_resume', '0014_journal_publication_indexed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forward',
            field=models.BooleanField(default=False),
        ),
    ]
